### ISSUE TITLE
Needs a runtime.txt file for launching at MyBinder.org

### ISSUE THREAD

**Issue by fomightez** [DessimozLab/OmaDB#2]
For the Binder badge to launch an instance that should work, according to https://repo2docker.readthedocs.io/en/latest/config_files.html#description-install-an-r-package you need a `runtime.txt` file in addition to your `DESCRIPTION` file. You can optionally use the line where you specify a snapshot at MRAN to specify the R version, see newer documentation at https://github.com/binder-examples/r .

I just tried launching and it ends up with version of R 3.4.4, it seems and it won't work for first cell. I stoped there.

**Comment by alpae** [comment]
@fomightez thanks for letting us know. I've added the necessary files (runtime.txt and install.R) and it seems to work now on binder.
